# Site settings
title: Amperia Productions
email: info@amperiaproductions.nl
description: > # this means to ignore newlines until "baseurl:"
  Martijn moet nog een awesome ding voor schrijven, maar tot die tijd blijft dit hier staan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://beta.amperiaproductions.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
